# Generated by Django 4.1 on 2022-12-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                ("total_followers", models.IntegerField(default=0)),
                ("total_upvote", models.IntegerField(default=0)),
                ("total_downvote", models.IntegerField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-updated", "-created"],},
        ),
    ]
