# Generated by Django 4.1.3 on 2022-11-30 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='room',
            name='followers',
            field=models.ManyToManyField(related_name='room_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
    ]
