# Generated by Django 4.1.3 on 2022-12-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.topics'),
        ),
    ]
