# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_rename_user_room_creator_room_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='followers',
        ),
    ]
