# Generated by Django 4.1.3 on 2022-12-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_room_topic'),
        ('room', '0003_topic_alter_room_options_room_created_room_updated_and_more'),
    ]

    operations = [
    ]
