# Generated by Django 4.1.3 on 2022-12-01 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_followers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_requests_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
