# Generated by Django 4.1 on 2022-12-09 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="topic_creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topics",
            name="topic_followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_requests_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
