# Generated by Django 4.1.3 on 2022-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_room_topic'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following_room',
            field=models.ManyToManyField(null=True, to='room.room'),
        ),
    ]
