# Generated by Django 4.1.3 on 2022-12-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_follower_user_user_following_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_follower_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_following_user',
            field=models.IntegerField(default=0),
        ),
    ]
