# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_room_followers'),
        ('user', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_room',
            field=models.ManyToManyField(to='room.room'),
        ),
    ]
